//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.NationalityService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NationalityService.INationality")]
    public interface INationality {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/Message", ReplyAction="http://tempuri.org/INationality/MessageResponse")]
        string Message();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/Message", ReplyAction="http://tempuri.org/INationality/MessageResponse")]
        System.Threading.Tasks.Task<string> MessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/GetNationalities", ReplyAction="http://tempuri.org/INationality/GetNationalitiesResponse")]
        ApplicationService.DTOs.NationalityDTO[] GetNationalities();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/GetNationalities", ReplyAction="http://tempuri.org/INationality/GetNationalitiesResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.NationalityDTO[]> GetNationalitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/GetNationalityByID", ReplyAction="http://tempuri.org/INationality/GetNationalityByIDResponse")]
        ApplicationService.DTOs.NationalityDTO GetNationalityByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/GetNationalityByID", ReplyAction="http://tempuri.org/INationality/GetNationalityByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.NationalityDTO> GetNationalityByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/PostNationality", ReplyAction="http://tempuri.org/INationality/PostNationalityResponse")]
        string PostNationality(ApplicationService.DTOs.NationalityDTO nationalityDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/PostNationality", ReplyAction="http://tempuri.org/INationality/PostNationalityResponse")]
        System.Threading.Tasks.Task<string> PostNationalityAsync(ApplicationService.DTOs.NationalityDTO nationalityDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/PutNationality", ReplyAction="http://tempuri.org/INationality/PutNationalityResponse")]
        string PutNationality(ApplicationService.DTOs.NationalityDTO nationalityDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/PutNationality", ReplyAction="http://tempuri.org/INationality/PutNationalityResponse")]
        System.Threading.Tasks.Task<string> PutNationalityAsync(ApplicationService.DTOs.NationalityDTO nationalityDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/DeleteNationality", ReplyAction="http://tempuri.org/INationality/DeleteNationalityResponse")]
        string DeleteNationality(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INationality/DeleteNationality", ReplyAction="http://tempuri.org/INationality/DeleteNationalityResponse")]
        System.Threading.Tasks.Task<string> DeleteNationalityAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INationalityChannel : MVC.NationalityService.INationality, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NationalityClient : System.ServiceModel.ClientBase<MVC.NationalityService.INationality>, MVC.NationalityService.INationality {
        
        public NationalityClient() {
        }
        
        public NationalityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NationalityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NationalityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Message() {
            return base.Channel.Message();
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync() {
            return base.Channel.MessageAsync();
        }
        
        public ApplicationService.DTOs.NationalityDTO[] GetNationalities() {
            return base.Channel.GetNationalities();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.NationalityDTO[]> GetNationalitiesAsync() {
            return base.Channel.GetNationalitiesAsync();
        }
        
        public ApplicationService.DTOs.NationalityDTO GetNationalityByID(int id) {
            return base.Channel.GetNationalityByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.NationalityDTO> GetNationalityByIDAsync(int id) {
            return base.Channel.GetNationalityByIDAsync(id);
        }
        
        public string PostNationality(ApplicationService.DTOs.NationalityDTO nationalityDto) {
            return base.Channel.PostNationality(nationalityDto);
        }
        
        public System.Threading.Tasks.Task<string> PostNationalityAsync(ApplicationService.DTOs.NationalityDTO nationalityDto) {
            return base.Channel.PostNationalityAsync(nationalityDto);
        }
        
        public string PutNationality(ApplicationService.DTOs.NationalityDTO nationalityDto) {
            return base.Channel.PutNationality(nationalityDto);
        }
        
        public System.Threading.Tasks.Task<string> PutNationalityAsync(ApplicationService.DTOs.NationalityDTO nationalityDto) {
            return base.Channel.PutNationalityAsync(nationalityDto);
        }
        
        public string DeleteNationality(int id) {
            return base.Channel.DeleteNationality(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteNationalityAsync(int id) {
            return base.Channel.DeleteNationalityAsync(id);
        }
    }
}
