//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.StudentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentService.IStudent")]
    public interface IStudent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Message", ReplyAction="http://tempuri.org/IStudent/MessageResponse")]
        string Message();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/Message", ReplyAction="http://tempuri.org/IStudent/MessageResponse")]
        System.Threading.Tasks.Task<string> MessageAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudents", ReplyAction="http://tempuri.org/IStudent/GetStudentsResponse")]
        ApplicationService.DTOs.StudentDTO[] GetStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudents", ReplyAction="http://tempuri.org/IStudent/GetStudentsResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.StudentDTO[]> GetStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentByID", ReplyAction="http://tempuri.org/IStudent/GetStudentByIDResponse")]
        ApplicationService.DTOs.StudentDTO GetStudentByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/GetStudentByID", ReplyAction="http://tempuri.org/IStudent/GetStudentByIDResponse")]
        System.Threading.Tasks.Task<ApplicationService.DTOs.StudentDTO> GetStudentByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/PostStudent", ReplyAction="http://tempuri.org/IStudent/PostStudentResponse")]
        string PostStudent(ApplicationService.DTOs.StudentDTO studentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/PostStudent", ReplyAction="http://tempuri.org/IStudent/PostStudentResponse")]
        System.Threading.Tasks.Task<string> PostStudentAsync(ApplicationService.DTOs.StudentDTO studentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/PutStudent", ReplyAction="http://tempuri.org/IStudent/PutStudentResponse")]
        string PutStudent(ApplicationService.DTOs.StudentDTO studentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/PutStudent", ReplyAction="http://tempuri.org/IStudent/PutStudentResponse")]
        System.Threading.Tasks.Task<string> PutStudentAsync(ApplicationService.DTOs.StudentDTO studentDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/DeleteStudent", ReplyAction="http://tempuri.org/IStudent/DeleteStudentResponse")]
        string DeleteStudent(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudent/DeleteStudent", ReplyAction="http://tempuri.org/IStudent/DeleteStudentResponse")]
        System.Threading.Tasks.Task<string> DeleteStudentAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentChannel : MVC.StudentService.IStudent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentClient : System.ServiceModel.ClientBase<MVC.StudentService.IStudent>, MVC.StudentService.IStudent {
        
        public StudentClient() {
        }
        
        public StudentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Message() {
            return base.Channel.Message();
        }
        
        public System.Threading.Tasks.Task<string> MessageAsync() {
            return base.Channel.MessageAsync();
        }
        
        public ApplicationService.DTOs.StudentDTO[] GetStudents() {
            return base.Channel.GetStudents();
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.StudentDTO[]> GetStudentsAsync() {
            return base.Channel.GetStudentsAsync();
        }
        
        public ApplicationService.DTOs.StudentDTO GetStudentByID(int id) {
            return base.Channel.GetStudentByID(id);
        }
        
        public System.Threading.Tasks.Task<ApplicationService.DTOs.StudentDTO> GetStudentByIDAsync(int id) {
            return base.Channel.GetStudentByIDAsync(id);
        }
        
        public string PostStudent(ApplicationService.DTOs.StudentDTO studentDto) {
            return base.Channel.PostStudent(studentDto);
        }
        
        public System.Threading.Tasks.Task<string> PostStudentAsync(ApplicationService.DTOs.StudentDTO studentDto) {
            return base.Channel.PostStudentAsync(studentDto);
        }
        
        public string PutStudent(ApplicationService.DTOs.StudentDTO studentDto) {
            return base.Channel.PutStudent(studentDto);
        }
        
        public System.Threading.Tasks.Task<string> PutStudentAsync(ApplicationService.DTOs.StudentDTO studentDto) {
            return base.Channel.PutStudentAsync(studentDto);
        }
        
        public string DeleteStudent(int id) {
            return base.Channel.DeleteStudent(id);
        }
        
        public System.Threading.Tasks.Task<string> DeleteStudentAsync(int id) {
            return base.Channel.DeleteStudentAsync(id);
        }
    }
}
